Make *.Install_NotOverInstall test ignore file order
google/omaha pull request #322
Opened 2021-09-21 18:25 UTC by sparist

When the files are named differently than the Google defaults, the ordering changes.
This commit changes the test to ignore ordering changes.

Fixes: #321

2021-09-23 02:37 UTC, Karpativ9 requested changes

2021-09-23 02:37 UTC, Karpativ9 commented on omaha/setup/setup_files_unittest.cc
> +    EXPECT_NE(
This

2021-09-23 03:37 UTC, sparist commented on omaha/setup/setup_files_unittest.cc
> +    EXPECT_NE(
Not sure I understand

2021-09-25 00:06 UTC, merged

2021-09-25 00:06 UTC, sorinj commented
thank you!

2021-09-25 03:57 UTC, syahril920827 commented
Hai

2021-09-25 03:58 UTC, syahril920827 commented
Hai

2021-09-25 04:02 UTC, syahril920827 commented on omaha/setup/setup_files_unittest.cc
> +    EXPECT_NE(
Hai

2021-09-25 09:08 UTC, syahril920827 commented
Pada Sab, 25 Sep 2021 12:02 PTG Muhammad Syahril Bin md saad <
***@***.***> menulis:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In omaha/setup/setup_files_unittest.cc
> <https://github.com/google/omaha/pull/322#discussion_r715986047>:
>
> > +        extra_files.find(_T("goopdateres_iw.dll")), extra_files.end());
> +    EXPECT_NE(
> +        extra_files.find(_T("goopdateres_ja.dll")), extra_files.end());
> +    EXPECT_NE(
> +        extra_files.find(_T("goopdateres_kn.dll")), extra_files.end());
> +    EXPECT_NE(
> +        extra_files.find(_T("goopdateres_ko.dll")), extra_files.end());
> +    EXPECT_NE(
> +        extra_files.find(_T("goopdateres_lt.dll")), extra_files.end());
> +    EXPECT_NE(
> +        extra_files.find(_T("goopdateres_lv.dll")), extra_files.end());
> +    EXPECT_NE(
> +        extra_files.find(_T("goopdateres_ml.dll")), extra_files.end());
> +    EXPECT_NE(
> +        extra_files.find(_T("goopdateres_mr.dll")), extra_files.end());
> +    EXPECT_NE(
>
> Hai
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/google/omaha/pull/322#discussion_r715986047>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AROOH6GNS6CNGFNY4XAG7FLUDVCVFANCNFSM5EPGO3XQ>
> .
>